name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change this back to 11 if that's what you intended
          distribution: 'adopt'

      - name: Compile and Test
        run: |
          javac SimpleAdder.java
          java SimpleAdder